# -*- coding: utf-8 -*-
"""EDA-day-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKWXrfnO5qUX5wdiZvZkEx4CoD9C4rwO
"""

#loading file
from google.colab import files
uploaded = files.upload()

#importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
 # Stop warnings
import warnings
warnings.filterwarnings('ignore')

#loading dataset
data = pd.read_csv('State wise Sexual Assault (Detailed) 1999 - 2013.csv')

# View the first few rows to get an overview of the data
print(data.head())

# Examine data types and check for missing values
print(data.info())

# Get summary statistics
print(data.describe())

# Get the column names
print("column names-",data.columns)

# Check the shape of the data
print(data.shape)

# Check for missing values
print(data.isnull().sum())

# Handling Missing Values (Example: Fill with mean for a specific column)
# Convert the column to numeric, handling errors
data['No. Of Cases In Which Offenders Were Known To The Victims'] = pd.to_numeric(data['No. Of Cases In Which Offenders Were Known To The Victims'], errors='coerce')
# Now fill NaN values with the mean
data['No. Of Cases In Which Offenders Were Known To The Victims'].fillna(
    data['No. Of Cases In Which Offenders Were Known To The Victims'].mean(),
    inplace=True
)

# Univariate Analysis of Yearly Counts
plt.figure(figsize=(10, 6))
sns.histplot(data['No. Of Cases In Which Offenders Were Known To The Victims'], bins=20, kde=True)
plt.title('Distribution of Yearly Counts')
plt

import seaborn as sns
import matplotlib.pyplot as plt

# Scatter plot to visualize the relationship between two numerical variables

sns.scatterplot(x='No. Of Cases In Which Offenders Were Known To The Victims', y='Total Cases', data=data)
plt.title('Scatter Plot of Cases with Known Offenders vs. Total Cases')
plt.show()

# Box plot to compare the distribution of a numerical variable across different categories

sns.boxplot(x='Year', y='No. Of Cases In Which Offenders Were Known To The Victims', data=data)
plt.title('Box Plot of Cases with Known Offenders by Year')
plt.xticks(rotation=45)
plt.show()

# Sum across years for each state
yearly_counts = data.groupby('State')['No. Of Cases In Which Offenders Were Known To The Victims'].sum()

# Modify the groupby operation to use the correct column name
yearly_counts = data.groupby('STATE/UT')['No. Of Cases In Which Offenders Were Known To The Victims'].sum()

#Comparative Analysis Across Years:
plt.figure(figsize=(12, 6))
sns.barplot(x=yearly_counts.index, y=yearly_counts.values)
plt.xticks(rotation=90)
plt.xlabel('State/UT')
plt.ylabel('Total Yearly Counts')
plt.title('Comparative Analysis Across Years')
plt.show()

# Calculate correlation matrix across years, excluding non-numeric columns
correlation_matrix = data.select_dtypes(include=np.number).corr()

# Select numerical columns for correlation analysis using iloc
# Assuming the first column is 'STATE/UT' and needs to be excluded
correlation = data.iloc[:, 1:].select_dtypes(include=np.number).corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation, annot=True, cmap="Blues")
plt.title("Correlation Between Case Counts by Year")
plt.show()

data.rename(columns={'STATE/UT': 'State_UT'}, inplace=True)
numeric_data = data.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

# Calculate the sum of numeric columns, handling NaNs
data['Total Cases'] = numeric_data.sum(axis=1)

# Select the top 5 states with the highest total cases
top_5_states = data.nlargest(5, 'Total Cases')

# Set 'States/ UTs' as index to make the plotting easier
top_5_states.set_index("State_UT", inplace=True)

# Transpose the DataFrame to have years as rows and states as columns
top_5_states = top_5_states.iloc[:, :-1].T

# Plot the grouped bar chart
top_5_states.plot(kind='bar', figsize=(15, 8), width=0.8)
plt.title("Yearly Trend of Cases in Top 5 States with Highest Rape Cases (2015-2020)")
plt.xlabel("Year")
plt.ylabel("Number of Cases")
plt.legend(title="States", loc="upper left")
plt.xticks(rotation=0)
plt.show()